Fixed bugs in p2 attach

diff --git a/p2 b/p2
--- a/p2
+++ b/p2
@@ -89,25 +89,24 @@ OPTIONS:
     mkdir $ROOT/${box_name} 2> /dev/null
     printf "Directory located at: $ROOT/${box_name}\n"
 
-    docker run -it -d \
-        -h ${box_name} \
-        --name ${box_name} \
-        --privileged \
-        --mount type=bind,source="$ROOT/${box_name}",target=/mnt/shared \
-        $env $port $volume \
-        platypew/pwnbox2 2> /dev/null
-
-    if [ $? -ne 0 ]; then
+    if [ $(docker ps -a --filter "name=^/${box_name}$" --format '{{.Names}}') ]; then
         printf "Container exists, reattaching...\n"
         docker start ${box_name} > /dev/null
-    fi
+    else
+        docker run -it -d \
+            -h ${box_name} \
+            --name ${box_name} \
+            --privileged \
+            --mount type=bind,source="$ROOT/${box_name}",target=/mnt/shared \
+            $env $port $volume \
+            platypew/pwnbox2 2> /dev/null
 
+        if [ $? -ne 0 ]; then
+            printf "An error has occured. Check arguments\n\n"
+            AUSE
+        fi
+    fi
     docker attach ${box_name}
-
-    if [ $? -ne 0 ]; then
-        printf "An error has occured. Check arguments\n\n"
-        AUSE
-    fi
 }
 
 RM() {
